#  A 
 
## AI-driven Adaptive Learning

<dfn>Ai-driven systems provide a more personalised learning experience which cater to diverse learning preferences/requirements.</dfn>

**Long Definition:** Ai-driven adaptive learning enhances student engagement and performance, scaffolding individual learner pathways in real-time based on performance and preference. It requires technology to diagnose a starting point for learners in terms of their existing knowledge and skills. Subsequently upskilling them and continually monitoring their performance. The systems provide immediate feedback to the students, which informs their subsequent learning tasks.











**Deep Dive:** 



**Contributors:** Vicki Dale

**Tags:** NA
 
## Accreditation

<dfn>A quality assurance and enhancement mechanism for programmes/courses by a relevant institution/external professional body, to ensure standards.</dfn>

**Long Definition:** 











**Deep Dive:** Accreditation can mean different things/be applied differently in different academic disciplines.  The [QAA website](https://www.qaa.ac.uk/reviewing-higher-education/degree-awarding-powers-and-university-title) gives more information about the general degree awarding powers that universities hold. Some schools/departments within a university will be accredited by an organisation (for example, the Adam Smith Business School at the University of Glasgow is accredited by AACSB, EQUIS, and AMBA), whereas in other areas, some degrees are accredited by professional bodies/organisations. This means that they are aligned with the professional body’s own qualifications and ensures that the education programme meets industry standards. Examples include the City Planning and Real Estate Msc degrees at the University of Glasgow are accredited by the [Royal Town Planning Institute (RTPI)](http://www.rtpi.org.uk https://www.rtpi.org.uk/become-a-planner/study-at-university/wales-scotland-and-northern-ireland/) and the [Royal Institute for Chartered Surveyors](https://www.rics.org https://www.rics.org/surveyor-careers/how-to-become-a-surveyor/university-surveying-courses) Other example include medicine and dentistry.



**Contributors:** Joanna Stewart, Alison McCandlish

**Tags:** NA
 
## Active Learning

<dfn>Learning by doing and reflection; this could be individual or collaborative.</dfn>

**Long Definition:** Active learning is defined as “any instructional method that engages students in the learning process….[it] requires students to do meaningful activities and think about what they are doing” (prince, 2004, p.233, citing bonwell and eison 1991).











**Deep Dive:** Active learning can take place in any format, including online or in-person.  There is a large variety of methods and strategies that can be employed. e.g., team-based learning, think, pair, share and problem-based learning. Active learning supports various skills such as critical thinking, problem-solving, teamwork, communication and collaboration. Active learning facilitates deep learning vs superficial learning.



**Contributors:** Vicki Dale

**Tags:** NA
 
## Assessment

<dfn>Method for evaluating learning and skills of learners</dfn>

**Long Definition:** Various methods for evaluating the learning that has taken place during a course, module or programme of study. Typically centered on demonstrating how the intended learning objectives of a course have been met, but also includes skills in communication that a student developed through a course











**Deep Dive:** While the goal is often to measure the attainment of learning objectives, something teachers forget to do is to align their assessment with those objectives or in other cases, the method of assessment can rely on a student needing to develop skills in communication that are assumed/not explicitly taught. The process of constructive alignment can help to align teaching methods and assessments with intended learning outcomes.



**Contributors:** Helena Paterson

**Tags:** hidden curriculum; pedagogy
 
## Asynchronous Learning

<dfn>Learning within the same module that occurs at different times for different students.</dfn>

**Long Definition:** Asynchronous learning refers to students accessing materials at their own pace/in their own time  (for example, watching pre-recorded lectures or doing readings).











**Deep Dive:** 



**Contributors:** Joanna Stewart

**Tags:** NA
