#  Data analysis report 
 
## Translation

**Gold standard for Professional Practice:** Translating written work from another language into English.  Students who are not native English speakers will often need to translate their thoughts from their primary language to English. The gold standard is to write the text in English from the start but where this creates challenges that compromise demonstration of learning, translation might be necessary. Support is available through English as a second language support, and feedback from staff or peers.

**How GenAI can be helpful (good practice):** GenAI offers sophisticated enhancement of translation software, and this is an expanding field that has significant future implications for communication across language barriers. Use GenAI-powered translation software to assit with translation of original work that you produce in another language to English (unless the testing of English Language is an ILO). Note that the nuance of an intended communication is likely to be lost or changed during any AI-assisted translation process so output should be carefully edited and refined. You can use it to help you to understand where you are making common mistakes in your use of English, to help to improve your writing in the future.  Good practice means using GenAI to help you to express your ideas more clearly but it should not be used to replace your own writing. 

**How GenAI can pose risks (poor practice):** Using GenAI for translation without knowing enough English to intepret meanings risks mispresentation of your ideas, or altering credit given via in-text citations. Translation should not be used as a replacement of learning to clearly communicate in English.  Failing to critically check outputs also risks miscommunicating field-specific terminology or using inappropriate terminology for your discipline. Over-reliance on GenAI limits your opportunity for practicing and improving communication in English, as well as confidence in the use of scientific and technical English.

**Skill-specific Assessment:** Translation decision log, Error detection exercise

**Main Skills Category:** Communication

---
