---
engine: knitr
---

# Overview {.unnumbered}

The **Assessment Skills Map for GenAI-use** is a toolkit developed within the Generative AI Network for Education (GAINEd) community of practice for the College of Medical, Veterinary & Life Sciences (MVLS), University of Glasgow. The toolkit supports educators in designing, reviewing, and communicating assessment expectations that take account of the merging role of generative AI (GenAI) in higher education and professional practice. We present it as an interactive toolkit with four parts.

- Part 1: Skills directory where we orgnise the skills along common skill domains.
- Part 2: Assessment directory where we link the skills to common assessments.
- Part 3: Practical uses such as statements on use of AI in assessment briefs, and acknowledgement of use of AI.
- Part 4: Skill progression where we developed a case study of programmatic skills progression based on report writing.

We have centered assessment design on discipline-specific skills rather than tasks, the map promotes programme-wide consistency, provides a shared language for staff and students, and reduces reliance on individual educators’ fluency in GenAI. It also serves as a practical tool for aligning local assessment design with institutional policy on responsible generative AI use in education.

## How to use the toolkit

The toolkit has been developed with the aim of providing a flexible resource for staff to be able to set clear and transparent advice to students about the benefits and implications of incorporating GenAI into their learning strategies.

Initially, 30 recurring core skills were identified that will be updated as needed. For each skill, the map highlights areas where GenAI can be constructively integrated in line with good professional practice, and where it may pose risks of poor practice or inappropriate substitution in relation to learning outcomes. We also suggests skills-specific assessment types that can measure competency more directly than traditional approaches to assist in assessment redesign.

### Directories for staff use

The **skills directory** is organised by competency categories (left-hand index), including lists of individual skills (right hand index), with advice on good and poor practice, examples of traditional assessment types into which they might be incorporated, and suggestions for redesigned assessments that more directly develop the skill. 

The **assessment directory** is organised by common assessment types (left-hand index), broken down into an index of component skills (right-hand index). Along with gold standard for professional practice, good and poor practice for use of GenAI, each skill incudes a list of skills-based redesigned assessments and the main skills category for the competency.

### Practical uses to develop student-facing advice

In the **practical use** section, examples have been provided to assist with writing student-facing statements about expected use of AI and acknowledging use. 

- **Expectations on use of GenAI** are student-facing statements customised to particular assessment types based on the combination of their underlying component skills.  Some examples of assessment types have been provided that combine sets of skills, to inform these statements about use of GenAI.  An important aim of the toolkit is that it will enable you to design your own combination of skills for particular assessments that are not represented.

- **Acknowledgement statements** are designed for students to transparently declare whether and how they have used GenAI tools, to properly attribute sources. Rather than focusing on the punitive consequences of misrepresenting attribution, these should allow students to share their good practice and reflect on which tools were useful for particular tasks.

### Skills Progression Framework

The **skills progression** section provides a **model** for considering how particular skillsets might be expected to develop progressively during the student academic journey, particularly considering good and poor practice in use of GenAI, along with other aspects of development of independence and expertise.  The **case study** provides an example of this framework applied to research-related skills during a four-year animal biology degree.

The resource is open for adaptation and reuse under a Creative Commons Attribution–ShareAlike 4.0 (CC BY-SA 4.0) licence

**Last edited:** `r Sys.Date()`
